sudo: false
language: node_js
node_js:
  - 14 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 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
  keep-history: true
  on:
    branch: main
  local-dir: public
